import type { Product } from '~/types';

export default defineEventHandler((): Product[] => [
  // Tops
  {
    id: 1,
    name: 'Cross Back Performance Bra',
    href: '#',
    imageSrc: '/images/products/image-26.png',
    imageAlt: "Front of women's Cross Back Performance Bra in black.",
    price: '€45',
    color: 'Black',
    category: 'top',
  },
  {
    id: 2,
    name: 'Rib Tank',
    href: '#',
    imageSrc: '/images/products/image-17.png',
    imageAlt: 'White rib tank top.',
    price: '€35',
    color: 'White',
    category: 'top',
  },
  {
    id: 3,
    name: 'Short Sleeve Fitted Tee',
    href: '#',
    imageSrc: '/images/products/image-15.png',
    imageAlt: 'Short sleeve fitted tee in sage.',
    price: '€42',
    color: 'Sage',
    category: 'top',
  },
    {
    id: 4,
    name: 'Cross Back Performance Bra',
    href: '#',
    imageSrc: '/images/products/image-28.png',
    imageAlt: "Front of women's Cross Back Performance Bra in Dewberry.",
    price: '€45',
    color: 'Dewberry',
    category: 'top',
  },
   {
    id: 5,
    name: 'Rib Tank',
    href: '#',
    imageSrc: '/images/products/image-52.png',
    imageAlt: 'Ocean blue rib tank top.',
    price: '€35',
    color: 'Ocean',
    category: 'top',
  },
   {
    id: 6,
    name: 'Cross Back Performance Bra',
    href: '#',
    imageSrc: '/images/products/image-33.png',
    imageAlt: "Camo dewberry performance bra.",
    price: '€45',
    color: 'Camo Dewberry',
    category: 'top',
  },
  // Bottoms
  {
    id: 7,
    name: 'Curved Seam Side Legging',
    href: '#',
    imageSrc: '/images/products/image-38.png',
    imageAlt: 'Sage green yoga leggings.',
    price: '€65',
    color: 'Sage',
    category: 'bottom',
  },
  {
    id: 8,
    name: '5" Biker Short',
    href: '#',
    imageSrc: '/images/products/image-18.png',
    imageAlt: 'Woman wearing camo dewberry biker shorts.',
    price: '€45',
    color: 'Camo Dewberry',
    category: 'bottom',
  },
  {
    id: 9,
    name: 'Curved Seam Side Legging',
    href: '#',
    imageSrc: '/images/products/image-52.png',
    imageAlt: 'Ocean blue yoga leggings.',
    price: '€65',
    color: 'Ocean',
    category: 'bottom',
  },
  {
    id: 10,
    name: 'Curved Seam Side Legging',
    href: '#',
    imageSrc: '/images/products/image-34.png',
    imageAlt: 'Stone colored yoga leggings.',
    price: '€65',
    color: 'Stone',
    category: 'bottom',
  },
  {
    id: 11,
    name: 'Curved Seam Side Legging',
    href: '#',
    imageSrc: '/images/products/image-27.png',
    imageAlt: 'Dewberry colored yoga leggings.',
    price: '€65',
    color: 'Dewberry',
    category: 'bottom',
  },
  {
    id: 12,
    name: 'Curved Seam Side Legging',
    href: '#',
    imageSrc: '/images/products/image-44.png',
    imageAlt: 'Violet colored yoga leggings.',
    price: '€65',
    color: 'Violet',
    category: 'bottom',
  },
  // Jackets
  {
    id: 13,
    name: 'Long Sleeve Zip Front Performance Jacket',
    href: '#',
    imageSrc: '/images/products/image-36.png',
    imageAlt: 'Sage green zip-front performance jacket.',
    price: '€85',
    color: 'Sage',
    category: 'jacket',
  },
  {
    id: 14,
    name: 'Long Sleeve Zip Front Performance Jacket',
    href: '#',
    imageSrc: '/images/products/image-28.png',
    imageAlt: 'Dewberry colored zip-front performance jacket.',
    price: '€85',
    color: 'Dewberry',
    category: 'jacket',
  }
]); 