import type { Activity } from '~/types';

export const activities: Activity[] = [
  {
    slug: 'monday-mindfulness',
    title: 'MONDAY MINDFULNESS',
    subtitle: 'Awakening the Mind',
    description: 'Yoga & Meditation Discovery Class',
    suitableFor: 'Beginners | Office Workers | Stress Relief Seekers',
    instructor: 'Ashley Lorenzo',
    highlights: [
      'Guided breathwork & mindfulness meditation',
      'Gentle Hatha sequences to awaken and energize the body',
      'Focus on relaxation and mental clarity',
      'Present-moment awareness practices'
    ],
    goal: 'Reconnect with inner peace and start your week with clarity and calmness.',
    image: '/images/activities/activity-monday.png',
    isFree: true,
    isMembersOnly: false,
    bgColor: '#fafaf5',
    titleColor: '#336666',
    subtitleColor: '#4d4d4d',
    descriptionColor: '#666666',
    textColor: '#4d4d4d',
    dividerColor: 'rgba(128,178,178,0.5)',
    time: '10:00 AM – 11:30 AM',
  },
  {
    slug: 'tuesday-therapy',
    title: 'TUESDAY THERAPY',
    subtitle: 'Shoulder & Neck Healing',
    description: 'Therapeutic Yoga Masterclass',
    suitableFor: 'Office workers | Neck/shoulder discomfort | Yoga therapy students',
    instructor: 'Jivana Heyman',
    highlights: [
      'Yoga props and alignment techniques for safe recovery',
      'Take-home techniques for daily tension relief',
      'Meditative poses for shoulder and neck release',
      'Restorative relaxation techniques'
    ],
    goal: 'Release physical tension and restore mobility for a pain-free life.',
    image: '/images/activities/activity-tuesday.png',
    isFree: true,
    isMembersOnly: false,
    bgColor: '#fafaf5',
    titleColor: '#336666',
    subtitleColor: '#4d4d4d',
    descriptionColor: '#666666',
    textColor: '#4d4d4d',
    dividerColor: 'rgba(128,178,178,0.5)',
    time: '1:00 PM – 2:30 PM'
  },
  {
    slug: 'wednesday-fusion',
    title: 'WEDNESDAY FUSION',
    subtitle: 'Balance Between Stillness & Motion',
    description: 'Fusion Flow',
    suitableFor: 'Intermediate practitioners | Strength & flexibility seekers',
    instructor: 'Georgia Weibel',
    highlights: [
      'A blend of Yin and Yang yoga: dynamic flows plus deep holds',
      'Strengthens endurance while encouraging deep tissue release',
      'Ideal for body-mind balance and injury prevention',
      'Combines active practice with restorative elements'
    ],
    goal: 'Find harmony between effort and ease in your practice and daily life.',
    image: '/images/activities/activity-wednesday.png',
    isFree: true,
    isMembersOnly: false,
    bgColor: '#fafaf5',
    titleColor: '#336666',
    subtitleColor: '#4d4d4d',
    descriptionColor: '#666666',
    textColor: '#4d4d4d',
    dividerColor: 'rgba(128,178,178,0.5)',
    time: '6:00 PM – 7:30 PM'
  },
  {
    slug: 'thursday-specialty',
    title: 'THURSDAY SPECIALTY',
    subtitle: 'Prenatal Yoga Private Experience',
    description: 'Specialty Class',
    suitableFor: 'Expectant mothers | Postnatal recovery',
    instructor: 'Tamika Caston-Miller',
    highlights: [
      'Safe movements tailored for pregnancy and postpartum',
      'Focus on pelvic floor recovery and breath awareness',
      'Emotional grounding techniques for motherhood',
      'Personalized guidance in a supportive environment'
    ],
    goal: 'Nurture your body and connect with your baby in a safe, supportive space.',
    image: '/images/activities/activity-thursday.png',
    isFree: true,
    isMembersOnly: false,
    bgColor: '#fafaf5',
    titleColor: '#336666',
    subtitleColor: '#4d4d4d',
    descriptionColor: '#666666',
    textColor: '#4d4d4d',
    dividerColor: 'rgba(128,178,178,0.5)',
    time: '11:00 AM – 12:00 PM'
  },
  {
    slug: 'friday-masterclass',
    title: 'FRIDAY MASTERCLASS',
    subtitle: 'Introduction to Ashtanga Fundamentals',
    description: 'Advanced Practice',
    suitableFor: 'Intermediate to advanced students | Physical challenge seekers',
    instructor: 'Vytas Baskauskas',
    highlights: [
      'Introduction to the Primary Series of Ashtanga Yoga',
      'Synchronized breath, movement, and gaze (Drishti)',
      'Builds strength, stamina, and mental focus',
      'Traditional approach to dynamic yoga practice'
    ],
    goal: 'Challenge your limits and deepen your physical and mental discipline.',
    image: '/images/activities/activity-friday.png',
    isFree: true,
    isMembersOnly: false,
    bgColor: '#fafaf5',
    titleColor: '#336666',
    subtitleColor: '#4d4d4d',
    descriptionColor: '#666666',
    textColor: '#4d4d4d',
    dividerColor: 'rgba(128,178,178,0.5)',
    time: '4:00 PM – 5:30 PM'
  },
  {
    slug: 'saturday-family',
    title: 'SATURDAY FAMILY YOGA',
    subtitle: 'Joyful Bonding & Movement',
    description: 'Family Fun',
    suitableFor: 'Parents & kids (ages 4-10) | Beginner-friendly',
    instructor: 'Emily Carter',
    highlights: [
      'Fun and interactive yoga sequences for parents and children',
      'Breathwork and mindfulness games for kids',
      'Gentle partner yoga to enhance bonding',
      'Introduction to relaxation techniques for families'
    ],
    goal: 'Create lasting memories while introducing your children to the benefits of yoga.',
    image: '/images/activities/activity-saturday.png',
    isFree: true,
    isMembersOnly: false,
    bgColor: '#fafaf5',
    titleColor: '#336666',
    subtitleColor: '#4d4d4d',
    descriptionColor: '#666666',
    textColor: '#4d4d4d',
    dividerColor: 'rgba(128,178,178,0.5)',
    time: '9:30 AM – 10:30 AM'
  },
  {
    slug: 'sunday-sunrise',
    title: 'SUNDAY SUNRISE VINYASA',
    subtitle: 'Energizing Flow to Start Your Day',
    description: 'Outdoor Yoga',
    suitableFor: 'All levels | Early risers | Outdoor enthusiasts',
    instructor: 'Daniel Moreau',
    highlights: [
      'A dynamic flow to awaken the body and mind',
      'Focus on breath-to-movement synchronization',
      'Invigorating sun salutations to energize the day',
      'Closing meditation with nature sounds'
    ],
    goal: 'Energize your body and mind with the rising sun for a vibrant start to your Sunday.',
    image: '/images/activities/activity-sunday.png',
    isFree: true,
    isMembersOnly: false,
    bgColor: '#fafaf5',
    titleColor: '#336666',
    subtitleColor: '#4d4d4d',
    descriptionColor: '#666666',
    textColor: '#4d4d4d',
    dividerColor: 'rgba(128,178,178,0.5)',
    time: '7:00 AM – 8:15 AM'
  },
  {
    slug: 'members-exclusive',
    title: 'Deep Stretch & Sound Healing',
    subtitle: 'Yoga Immersion Experience',
    description: 'Exclusive Workshop',
    suitableFor: 'Yoga members | Deep relaxation seekers',
    instructor: 'Sophia Lin',
    highlights: [
      'Gentle Yin yoga with extended holds for deep muscle release',
      'Sound bath healing with Tibetan singing bowls',
      'Guided meditation to restore energy balance',
      'Aromatherapy-infused ambiance for full sensory relaxation'
    ],
    goal: 'Embark on a journey of deep relaxation and sensory renewal.',
    image: '/images/activities/activity-special.png',
    isFree: false,
    isMembersOnly: true,
    bgColor: '#f2f2fa',
    titleColor: '#4d4d99',
    subtitleColor: '#4d4d66',
    descriptionColor: '#666680',
    textColor: '#4d4d66',
    dividerColor: 'rgba(102,102,178,0.5)',
    time: '7:00 PM – 8:30 PM'
  }
]; 